name: SignEdit
main: de.sp1rit.signedit.SignEdit
version: 1.4
website: http://www.sp1rit.de
author: Sp1rit
description: >
             Remote-edit signs with Colors!
commands:
  se:
    description: Clears your own or a player's inventory.
    usage: |
           /<command>
           Example: /<command> - clears your own inventory.
           Example: /<command> Bukkit - clears Bukkit's inventory.
  signedit:
    description: Gives yourself or someone else items. Supports item IDs or names.
    usage: |
           /<command> item[:data] [amount] [player]
           Example: /<command> 2 - gives you 1 grass.
           Example: /<command> 2 20 - gives you 20 grass.
           Example: /<command> 2 -1 - gives you unlimited grass.
           Example: /<command> 2 64 Bukkit - gives a player named Bukkit 64 grass.
           Example: /<command> 35:12 200 - gives you 200 brown wool.
