name: SignEdit
main: de.sp1rit.signedit.SignEdit
version: 1.4.1
website: http://redmine.sp1rit.de
author: Sp1rit
description: >
             Remote-edit signs with Colors!
commands:
  se:
    description: Control all SignEdit features with one command.
    usage: |
           /<command>
           Example: /<command> - Shows the SignEdit-help.
  signedit:
    description: Control all SignEdit features with one command.
    usage: |
           /<command>
           Example: /<command> - Shows the SignEdit-help.
